export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";

export const PURCHASE_BURGER_REQUEST = "PURCHASE_BURGER_REQUEST";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";

export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST"; 
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS"; 
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL"; 

export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
